### ISSUE TITLE
Missing package.json File 

### ISSUE THREAD

**Issue by SneakyAssasin01** [WilliamWelsh/DominosDiscord#1]
C:\Users\Sarah\Downloads\Compressed\DominosDiscord-main\DominosDiscord-main>npm run DiscordOrder.cs
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Sarah\Downloads\Compressed\DominosDiscord-main\DominosDiscord-main/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Sarah\Downloads\Compressed\DominosDiscord-main\DominosDiscord-main\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sarah\AppData\Local\npm-cache\_logs\2021-11-29T16_39_22_461Z-debug.log

**Comment by WilliamWelsh** [comment]
This is a .NET Core project, there is no `package.json`. Packages are listed in [DominosDiscord.csproj](https://github.com/WilliamWelsh/DominosDiscord/blob/main/DominosDiscord.csproj). Fill out `Config.cs`, then run `dotnet restore` and then `dotnet run` (make sure you have [.NET 5](https://dotnet.microsoft.com/download/dotnet/5.0) installed). I updated the README if you need more help.

**Comment by SneakyAssasin01** [comment]
Yep, Imma dumbass, THx
